//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public bool expense_income { get; set; }
        public int amount { get; set; }
        public int category { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
        public int userid { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
